# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.1.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/